### ISSUE TITLE
Working on Objective-C projects ?

### ISSUE THREAD

**Issue by antwllm** [nicklockwood/Expression#10]
Hello,

I am trying to integrate this POD in my Objective-C.

I am facing some issues.

Can you help me please ?

**Comment by nicklockwood** [comment]
Hi @antwllm, Expression wasn't built with Objective-C compatibility in mind, so it probably won't work well in an Objective-C project.

You might be able to use it by writing some bridging code in Swift though. What is it that you want to do?

**Comment by antwllm** [comment]
Thank you for your quick answer @nicklockwood !

Yeah that's what I want.

I am wondering if any one tried before.
