### ISSUE TITLE
Square brackets

### ISSUE THREAD

**Issue by MichalNekvasil** [nicklockwood/Expression#30]
Hello, I have problem with evaluating expression with square brackets. 

In math it's OK to write [(10,3+10,1)*7]+3, but flee will not evaluate such expression..

Is there a way to make it work?

Thank you

P.S. of course I can replace square with round brackets, but it is not comfortable

**Comment by nicklockwood** [comment]
I suggest just preprocessing the expression string by replacing [ with ( and ] with ), e.g.

```
let expression = Expression(input.replacingOccurrences(of: "[", with: "(").replacingOccurrences(of: "]", with: ")"))
```
