### ISSUE TITLE
when using the sample code it won't execute

### ISSUE THREAD

**Issue by AWS-Drew** [nicklockwood/Expression#31]
the sample code cut from the description: 
var bar = 7 // variable
        let expression = Expression("bas + baz(5) + rnd()", symbols: [
            .variable("bar"): { _ in bar },
            .function("baz", arity: 1): { args in args[0] as! Int + 1 },
            .function("rnd", arity: 0): { _ in Double(arc4random()) }
        ])

Has this issue: "Type of expression is ambiguous without more context"  "Expression" is imported

**Comment by nicklockwood** [comment]
Are you also importing Foundation in the same file? Foundation also defines an Expression type.

**Comment by AWS-Drew** [comment]
In the view controller I have 4 imports....uikit, charts, Darwin, and expression

**Comment by AWS-Drew** [comment]
But I do have foundation called up in another file

**Comment by AWS-Drew** [comment]
Finally figured it out.  When cutting and pasting to try out the code, “Expression” was just not being recognized.  However, when typing it in, the format was instantly recognized
