### ISSUE TITLE
problem with swift build, missing 0.3.0 tag ?

### ISSUE THREAD

**Issue by frranck** [nicklockwood/Expression#4]
Hi,
If I'm trying to point to your repo, instead of my fork 
        .Package(url: "https://github.com/nicklockwood/Expression", Version(0,3,0))])
and run 
$ swift build

Cloning https://github.com/nicklockwood/Expression
error: No version tag found in (/Users/franck/dev/mrboom_pi/asm2c/Packages/Expression) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"

I get this error, I think it's because you're missing a tag "0.3.0"
If I try to use a 0.3 tag instead:

        .Package(url: "https://github.com/nicklockwood/Expression", Version(0,3))])

I get this error:                                                                    ^
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.

Could you please try to add a "0.3.0" tag ?

**Comment by nicklockwood** [comment]
Done.
