### ISSUE TITLE
Complex expressions are not working 

### ISSUE THREAD

**Issue by faizal-karim** [nicklockwood/Expression#51]
I have an expression like this -> **"(0.341 * 8000.0) / (1 - (1 + 0.341) ^ -84)"** , I used below code but giving wrong answer. 

Expected result - "109.71908469357446" 
Actual result - "1.538906384258725e-36"

Can someone please correct me? 

```
do {
            let result = try Expression(
                "(0.341 * 8000.0) / (1 - (1 + 0.341) ^ -84)",
                symbols: [
                    .infix("^"): { pow($0[0], $0[1]) }
                ]
            ).evaluate()

            print(result) 

        } catch {

        }
```

**Comment by nicklockwood** [comment]
@faizal-karim I think the issue here is that `^` has a the same precedence as `-` so the expression is evaluated as:

```swift
(0.341 * 8000.0) / ((1 - (1 + 0.341)) ^ -84)
```

I can fix this quickly by hard-coding a more appropriate precedence. In the longer term I really need to expose a way to set precedence for custom operators.

**Comment by nicklockwood** [comment]
@faizal-karim this is fixed in the latest version (0.13.8)

**Comment by jaydeepbhayani** [comment]
@nicklockwood what about android?

**Comment by nicklockwood** [comment]
@jaydeepbhayani what about it?

**Comment by jaydeepbhayani** [comment]
@nicklockwood do you have same library in android?

**Comment by nicklockwood** [comment]
@jaydeepbhayani no. I'm not sure what the state of Swift on Android is at the moment. In principle it might work, but it's not something I can help with.
