### ISSUE TITLE
There's now Foundation.Expression

### ISSUE THREAD

**Issue by nighthawk** [nicklockwood/Expression#52]
The day has come and this year there's a new addition to Foundation: [Foundation.Expression](https://developer.apple.com/documentation/foundation/expression).

That leads to a number of name clashes and for example the test suite doesn't compile due to:

> 'Expression' is ambiguous for type lookup in this context
> Found this candidate (Foundation.Expression)

What makes this tricky is that this library itself is called Expression, so you can't disambiguate by say replacing `Expression.Error` with `Expression.Expression.Error`.

@nicklockwood Any suggestions for how to best tackle this? Should this library be renamed?

**Comment by nicklockwood** [comment]
I've added a NumericExpression typealias that you can use as a workaround (see updated [README on the develop branch](https://github.com/nicklockwood/Expression/tree/develop?tab=readme-ov-file#integration))

**Comment by nighthawk** [comment]
Great, thank you very much, that works.

**Comment by nighthawk** [comment]
Fixed in 2bc0d1c15de43be99e2cdb7f5ed2c1d56e2a6417.

**Comment by engin7** [comment]
@nicklockwood  I'm not able to update cocoa pods to 0.13.9 
have you published the pod specs ?

**Comment by nicklockwood** [comment]
@engin7 sorry about that - try it now
