### ISSUE TITLE
variables with index

### ISSUE THREAD

**Issue by wildthink** [nicklockwood/Expression#8]
It would be great if we could support "myarray[1]" as a symbol. If you don't think its a good idea for the main branch could you offer a pointer to the best way to implement it anyway? :-)
thanks.

**Comment by nicklockwood** [comment]
It’s definitely something I want to support. The main issue I’m wrestling with is whether to make the [ ] part of the identifier (as I have with dots and quotes) or to make it a separate operator.

**Comment by wildthink** [comment]
Umm, making it an operator would be more swifty, corresponding to the subscript() method. Also, wouldn't being an operator be easier when the key (e.g. items[key]) might also be a symbol?

**Comment by nicklockwood** [comment]
@wildthink yes, the problem is that you can't subscript a number, which is all that Expression currently knows how to deal with.

**Comment by nicklockwood** [comment]
@wildthink I  guess for your use case, you'd want the subscript to be part of the symbol, in the same way that functions currently work. So you'd have something like

```swift
.subscript(name, arity:)
```

 That could work. It would mean you couldn't subscript the result of a function though, so you couldn't write an expression like:

```swift
foo(5)[6]
```

**Comment by wildthink** [comment]
On a separate but related note, I'm interested in supporting identifiers like x' (being a variant of x). Its something inspired by TLA+ (https://en.wikipedia.org/wiki/TLA%2B). Maybe adding a new enum type? Any pointers into the code to effect this would be welcome :-).

**Comment by nicklockwood** [comment]
@wildthink I don't think it's necessary to introduce a new enum type for that - it should just be possible for me to support symbols that include a trailing ', as it wouldn't be ambiguous with any other symbol. Would that work for you?

**Comment by wildthink** [comment]
That would be great. I'm just trying to be sensitive to your overall goals but if I don't have to maintain my own fork, all the better. :-)
thanks.

**Comment by nicklockwood** [comment]
@wildthink OK, both your feature requests are implemented in version 0.9.0 😊

**Comment by wildthink** [comment]
Wow! Thanks a bunch.
How much do I owe you? :-)

**Comment by nicklockwood** [comment]
This one’s on the house ;-)
